### ISSUE TITLE
`sessionToken.get()` from `useSessionToken` throws error: SessionTokenApiError: Error fetching session token.

### ISSUE THREAD

**Issue by jmacmillin** [Shopify/ui-extensions#1232]
## Please list the package(s) involved in the issue, and include the version you are using

`useSessionToken` version [2023-04](https://shopify.dev/docs/api/checkout-ui-extensions/2023-04/react-hooks/sessions/usesessiontoken) and [2023-07](https://shopify.dev/docs/api/checkout-ui-extensions/2023-07/react-hooks/sessions/usesessiontoken).

## Describe the bug

`sessionToken.get()` from `useExtensionApi` in version 2023-04 and `useApi` in version 2023-07 both throw this error when used in my Checkout UI extension:
```
SessionTokenApiError: Error fetching session token.
    at get (app.latest.en.340c72303db8bfc11763.js:1:337388)
    at async Object.call (842.latest.en.57e01a9c3afe5e857861.js:2:63319)
    at async MessagePort.b (842.latest.en.57e01a9c3afe5e857861.js:2:65892)
```
This error only occurs within the Checkout Extensibility builder (Admin -> Settings -> Checkout -> Customize) the first time `sessionToken.get()` is called, which occurs when I add my extension to Checkout (my Checkout UI extension calls this API on load). The error does not occur after adding the extension to Checkout, saving, and refreshing the Checkout builder.

## Steps to reproduce the behavior:

1. Open the Checkout Extensibility builder.
1. Open the browser console.
1. Add a Checkout UI extension that calls `sessionToken.get()` to my Shopify Checkout.

## Expected behavior

I expect `sessionToken.get()` to return a valid session token.

## Screenshots

Here's a screenshot of the error thrown:
<img width="644" alt="Screenshot 2023-08-14 at 10 03 15 PM" src="https://github.com/Shopify/ui-extensions/assets/104387372/818d7fcb-a6ca-4f8c-9a88-a1cbed16371f">

## Additional context

I've tried updating `useSessionToken` from version 2023-04 of [useExtensionApi](https://shopify.dev/docs/api/checkout-ui-extensions/2023-04/react-hooks/sessions/usesessiontoken) (imported from `@shopify/checkout-ui-extensions-react`) to version 2023-07 of [useApi](https://shopify.dev/docs/api/checkout-ui-extensions/2023-07/react-hooks/sessions/usesessiontoken) (imported from `@shopify/ui-extensions-react/checkout`) but that did not resolve the issue.

I've found two other issues that call out this error within github.com/Shopify: this [issue](https://github.com/Shopify/ui-extensions/issues/842) (linked in the comment thread of this [issue](https://github.com/Shopify/checkout-ui/issues/45)) calls out that the solution that worked was to regenerate the extension. I verified that a brand new extension that uses version 2023-07 of `useSessionToken` does not encounter the issue. I'd prefer to avoid regenerating my extension so that I can preserve the history of my extension.

**Comment by jmacmillin** [comment]
This is important context I forgot to include - my extension was created with `@shopify/app` version 3.45.0 back in April (it had a `shopify.ui.extension.toml` file when it was created).

**Comment by keiraarts** [comment]
Was this ever solved? @justinmacmillin

**Comment by justinmacmillin** [comment]
@keiraarts to my knowledge it was not, but I haven't tested it in several months. @vijay-singh should have more context on this if you have further questions!

**Comment by shaun-visser** [comment]
We're experiencing the same issue - it seems to work fine on the "draft" app but not on our "published" app.
![image](https://github.com/user-attachments/assets/813380c4-997e-4557-9e45-fc8cfe08f7b3)
We're using version 2024-04

**Comment by tomlober** [comment]
We're experiencing the same issue. We are using 2024-07 version

![Image](https://github.com/user-attachments/assets/b77bd864-1bc8-4002-a2a0-223f1afe2fb5)

We test on '@shopify/ui-extensions-react/customer-account' with useApi() or useSessionToken().
