### ISSUE TITLE
Modals do not work in Checkout UI Extension

### ISSUE THREAD

**Issue by SuspenseFallback** [Shopify/ui-extensions#1609]
## Please list the package(s) involved in the issue, and include the version you are using

checkout-ui-extensions v2023.10.x

## Describe the bug

When trying to render a modal in a button `overlay` prop (as the docs say), the component disappears and I get the following errors:

```
The above error occurred in the <Fragment> component:

    at BlockStack
    at BlockLayout
    at Banner
    at Extension (https://kathy-both-welfare-raised.trycloudflare.com/extensions/983a5e04-73bc-408b-b900-a138622dc34f/assets/wallet-client-connection.js:19563:15)
    at ErrorBoundary (https://kathy-both-welfare-raised.trycloudflare.com/extensions/983a5e04-73bc-408b-b900-a138622dc34f/assets/wallet-client-connection.js:19463:7)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
logCapturedError @ wallet-client-connection.js:9736
callback @ wallet-client-connection.js:9782
callCallback @ wallet-client-connection.js:6209
commitUpdateQueue @ wallet-client-connection.js:6226
commitLayoutEffectOnFiber @ wallet-client-connection.js:13036
commitLayoutMountEffects_complete @ wallet-client-connection.js:13990
commitLayoutEffects_begin @ wallet-client-connection.js:13979
commitLayoutEffects @ wallet-client-connection.js:13930
commitRootImpl @ wallet-client-connection.js:15724
commitRoot @ wallet-client-connection.js:15648
performSyncWorkOnRoot @ wallet-client-connection.js:15235
flushSyncCallbacks @ wallet-client-connection.js:4641
flushSyncCallbacksOnlyInLegacyMode @ wallet-client-connection.js:4626
scheduleUpdateOnFiber @ wallet-client-connection.js:14904
dispatchSetState @ wallet-client-connection.js:8726
(anonymous) @ wallet-client-connection.js:19571
wrappedFunction @ wallet-client-connection.js:18752
call @ ExtensionSandbox.latest.en.dc2be28f1f1bda31d535.worker.js:2
h @ ExtensionSandbox.latest.en.dc2be28f1f1bda31d535.worker.js:2
wallet-client-connection.js:19478 

Uncaught DOMException: Failed to execute 'postMessage' on 'MessagePort': Symbol(react.element) could not be cloned.
    at l (https://cdn.shopify.com/shopifycloud/checkout-web/assets/ExtensionSandbox.latest.en.dc2be28f1f1bda31d535.worker.js:2:230276)
    at Object.call (https://cdn.shopify.com/shopifycloud/checkout-web/assets/ExtensionSandbox.latest.en.dc2be28f1f1bda31d535.worker.js:2:229810)
    at v (https://cdn.shopify.com/shopifycloud/checkout-web/assets/ExtensionSandbox.latest.en.dc2be28f1f1bda31d535.worker.js:2:228860)
    at remote (https://kathy-both-welfare-raised.trycloudflare.com/extensions/983a5e04-73bc-408b-b900-a138622dc34f/assets/wallet-client-connection.js:18809:9)
    at perform (https://kathy-both-welfare-raised.trycloudflare.com/extensions/983a5e04-73bc-408b-b900-a138622dc34f/assets/wallet-client-connection.js:18641:7)
    at appendChild (https://kathy-both-welfare-raised.trycloudflare.com/extensions/983a5e04-73bc-408b-b900-a138622dc34f/assets/wallet-client-connection.js:18807:12)
    at append (https://kathy-both-welfare-raised.trycloudflare.com/extensions/983a5e04-73bc-408b-b900-a138622dc34f/assets/wallet-client-connection.js:18793:7)
    at Object.append (https://kathy-both-welfare-raised.trycloudflare.com/extensions/983a5e04-73bc-408b-b900-a138622dc34f/assets/wallet-client-connection.js:18538:36)
    at appendChild (https://kathy-both-welfare-raised.trycloudflare.com/extensions/983a5e04-73bc-408b-b900-a138622dc34f/assets/wallet-client-connection.js:19264:16)
    at insertOrAppendPlacementNode (https://kathy-both-welfare-raised.trycloudflare.com/extensions/983a5e04-73bc-408b-b900-a138622dc34f/assets/wallet-client-connection.js:13411:17)
componentDidCatch @ wallet-client-connection.js:19478
callback @ wallet-client-connection.js:9788
callCallback @ wallet-client-connection.js:6209
commitUpdateQueue @ wallet-client-connection.js:6226
commitLayoutEffectOnFiber @ wallet-client-connection.js:13036
commitLayoutMountEffects_complete @ wallet-client-connection.js:13990
commitLayoutEffects_begin @ wallet-client-connection.js:13979
commitLayoutEffects @ wallet-client-connection.js:13930
commitRootImpl @ wallet-client-connection.js:15724
commitRoot @ wallet-client-connection.js:15648
performSyncWorkOnRoot @ wallet-client-connection.js:15235
flushSyncCallbacks @ wallet-client-connection.js:4641
flushSyncCallbacksOnlyInLegacyMode @ wallet-client-connection.js:4626
scheduleUpdateOnFiber @ wallet-client-connection.js:14904
dispatchSetState @ wallet-client-connection.js:8726
(anonymous) @ wallet-client-connection.js:19571
wrappedFunction @ wallet-client-connection.js:18752
call @ ExtensionSandbox.latest.en.dc2be28f1f1bda31d535.worker.js:2
h @ ExtensionSandbox.latest.en.dc2be28f1f1bda31d535.worker.js:2
608.latest.en.53e6a31e2bca0dbc25ee.js:2 ExtensionUsageError: Uncaught 
    at app.latest.en.2750ad5504d5da949e68.js:1:471462
    at app.latest.en.2750ad5504d5da949e68.js:1:2492
    at Set.forEach (<anonymous>)
    at app.latest.en.2750ad5504d5da949e68.js:1:2464
    at MessagePort.<anonymous> (app.latest.en.2750ad5504d5da949e68.js:1:1105778)
```

<img width="505" alt="Screenshot 2023-12-17 at 10 49 03 AM" src="https://github.com/Shopify/ui-extensions/assets/86506971/d978bd7c-2a04-4fe1-b76a-2365dd5f36be">

## Steps to reproduce the behavior:

1. Create a checkout UI extension
2. Enter the following code:

```
<Button
    overlay={
      <Modal id="my-modal" padding title="Return policy">
        <TextBlock>
          We have a 30-day return policy, which means you have 30
          days after receiving your item to request a return.
        </TextBlock>
        <TextBlock>
          To be eligible for a return, your item must be in the
          same condition that you received it, unworn or unused,
          with tags, and in its original packaging. You’ll also
          need the receipt or proof of purchase.
        </TextBlock>
        <Button onPress={() => ui.overlay.close("my-modal")}>
          Close
        </Button>
      </Modal>
    }
  >
    Return policy
</Button>
```

## Expected behavior

The component renders and the modal opens.

## Additional context

This code is from the official documentation, and it doesn't work.

**Comment by SuspenseFallback** [comment]
[UPDATE] It's working now
