### ISSUE TITLE
customer account ui extensions: react-router-dom + suspense

### ISSUE THREAD

**Issue by mateusvahl** [Shopify/ui-extensions#2333]
# Customer account ui extensions

## Please list the package(s) involved in the issue, and include the version you are using

```tsx
// package.json
"@shopify/ui-extensions": "unstable",
"@shopify/ui-extensions-react": "unstable",
"react": "^18.0.0",
"react-router-dom": "6.26.1"
```

## Describe the bug

Our fullpage extension uses react-router-dom, we `defer({})` the route loader response to quick show a skeleton loader to customers, using both `<Suspense />` and `<Await />` as indicated in [docs](https://reactrouter.com/en/main/components/await), however, at the moment the promise resolves, an error is throw by the <Offscreen /> component :

```tsx
// Fullpage extension entry file
import { Banner, reactExtension } from '@shopify/ui-extensions-react/customer-account';
import { Suspense } from 'react';
import { Await, RouterProvider, createBrowserRouter, defer, useLoaderData } from 'react-router-dom';

const App = () => {
  const { data } = useLoaderData() as { data: Promise<void> };
  return (
    <Suspense fallback={<Banner title="Loading..." />}>
      <Await resolve={data} errorElement={<Banner title="Error" />} children={() => <Banner title="Hello world" />} />
    </Suspense>
  );
};

export default reactExtension('customer-account.page.render', () => {
  // @ts-ignore
  // See: https://github.com/remix-run/react-router/issues/11315
  self.window = {};
  self.document = {
    // @ts-expect-error
    createElement: () => null,
  };
  const router = createBrowserRouter(
    [
      {
        path: '*',
        element: <App />,
        loader: () =>
          defer({
            // resolve data in 2s
            data: new Promise(resolve => {
              setTimeout(() => {
                resolve([]);
              }, 2000);
            }),
          }),
      },
    ],
    {
      window: self,
    }
  );
  return <RouterProvider router={router} />;
});
```

Additionally, react-router-dom is not working without creating a minimal `window/document`:
Issue:  https://github.com/remix-run/react-router/issues/11315

```tsx
  self.window = {};
  self.document = {
    createElement: () => null,
  };
```
(It *_thinks_* you are running in the server when using [data actions](https://reactrouter.com/en/main/route/action))

## Screenshots
```tsx
971a78959bd21f32924a8792888eaca4.js:293 Error handled by React Router default ErrorBoundary: TypeError: G is not a function
    at Cx (971a78959bd21f32924a8792888eaca4.js:108:4291)
    at Av (971a78959bd21f32924a8792888eaca4.js:108:11225)
    at zo (971a78959bd21f32924a8792888eaca4.js:108:9216)
    at Av (971a78959bd21f32924a8792888eaca4.js:108:10678)
    at zo (971a78959bd21f32924a8792888eaca4.js:108:9216)
    at Av (971a78959bd21f32924a8792888eaca4.js:108:9339)
    at zo (971a78959bd21f32924a8792888eaca4.js:108:9216)
    at Av (971a78959bd21f32924a8792888eaca4.js:108:11308)
    at zo (971a78959bd21f32924a8792888eaca4.js:108:9216)
    at Av (971a78959bd21f32924a8792888eaca4.js:108:9339)
```
![Image](https://github.com/user-attachments/assets/54ff6762-f5fb-4302-9180-8d05078d79c8)

**Comment by 5h1rU** [comment]
@brianshen1990  This specific issue is beyond react-router, is more about suspense and the lack of support on customer accounts extension internals.

However at one point, the URL pasted below was valid, and there was even an example demonstrating the use of React Router with extensions. This was a key factor in our decision to incorporate React Router into our architecture.

[https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/apis/navigation#example-using-react-router-in-a-full-page-extension-(experimental)](https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/apis/navigation#example-using-react-router-in-a-full-page-extension-(experimental))

**Comment by brianshen1990** [comment]
We previously provided an example for the unstable version. However, as React Router continues to release new versions and there are many scenarios we have not fully tested, we decided to remove the examples to prevent any confusion.

We plan to allocate time to support React Router and potentially Suspense in the future, although the timeline is not yet confirmed. We will keep you updated once we begin working on these features. Thank you for your understanding.
