### ISSUE TITLE
SessionTokenApiError: Error fetching session token when using .get() method on SessionToken from useSessionToken

### ISSUE THREAD

**Issue by TheSecurityDev** [Shopify/ui-extensions#842]
## Please list the package(s) involved in the issue, and include the version you are using
` "@shopify/checkout-ui-extensions-react": "^0.24.0"`

## Describe the bug

When trying to fetch a session token with `useSessionToken` I'm getting the following error:
```
SessionTokenApiError: Error fetching session token.
    at get (app.latest.en.d532c13fecc06d89fa96.js:1:149345)
    at async Object.call (vendors-node_modules_bugsnag_js_browser_notifier_js-node_modules_shopify_checkout-telemetry-a-90e396.latest.en.fc614147667054c21405.js:2:131264)
    at async MessagePort.h (vendors-node_modules_bugsnag_js_browser_notifier_js-node_modules_shopify_checkout-telemetry-a-90e396.latest.en.fc614147667054c21405.js:2:133811)
```

## Steps to reproduce the behavior:

Import `useSessionToken` from `@shopify/checkout-ui-extensions-react`.

Use the following code in the Extension component:
```
  const sessionTokenGetter = useSessionToken();
  useEffect(() => {
    async function getSessionToken() {
      const sessionToken = await sessionTokenGetter.get();
      console.log("Session token:", sessionToken);
    }
    void getSessionToken();
  }, [sessionTokenGetter]);
```

## Expected behavior

Calling `.get()` should return the session token as described in the docs.

## Additional context

I do have `network_access = true`, although I don't know if it's required.

**Comment by TheSecurityDev** [comment]
More details:

I can see in the dev console network tab the following GraphQL request being made:

```gql
{
    query: "query CheckoutExtensionSessionToken($id:ID!){
          checkoutExtensionSessionToken(id:$id){
              value expiresIn
              __typename
          }
       }",
    variables: {
       id: "gid://shopify/App/123" 
    },
    operationName: "CheckoutExtensionSessionToken",
  };
```

Which returns a response of:

```{"data":{"checkoutExtensionSessionToken":null}}```

As you can see in the request, the App ID appears to be hardcoding a test value of '123' (that's obviously not my app ID).

**Comment by TheSecurityDev** [comment]
Ok, I solved the issue by regenerating the extension with the new CLI version.
