### ISSUE TITLE
Unable to load UI Extensions appmetafields on B2B checkouts

### ISSUE THREAD

**Issue by KTruong008** [Shopify/ui-extensions#951]
## Please list the package(s) involved in the issue, and include the version you are using

"@shopify/app": "^3.43.0",
"@shopify/checkout-ui-extensions-react": "0.24.0",

## Describe the bug

When loading Checkout UI Extensions on B2B checkouts the UI extensions fail to load properly

## Steps to reproduce the behavior:

1. Create B2B company and navigate to B2B checkout link
2. Use metafields in app extension?
3. Navigate to checkout

## Expected behavior

Checkout UI Extensions should load on B2B checkouts as they do on normal checkouts.

## Additional context

The console shows this error within B2B checkouts:

```
ExecutionError: GraphQL execution failed with errors: [
  {
    "message": "invalid id",
    "locations": [
      {
        "line": 1,
        "column": 155
      }
    ],
    "path": [
      "checkoutProfile",
      "populatedExtensionPoints",
      0,
      "activatedExtensions",
      0,
      "extension",
      "metafields"
    ]
  }
]
    at checkout-web-packages-packages_card-fields-react_src_hook_ts-packages_checkout-graphql_src_in-92a386.latest.en.585aeb6f583627ae41f3.js:1:8962
    at async s.fetch (app.latest.en.d8134cfd7ee2b0d47f99.js:1:285834)
    at async s.run (checkout-web-packages-packages_card-fields-react_src_hook_ts-packages_checkout-graphql_src_in-92a386.latest.en.585aeb6f583627ae41f3.js:1:11181)
    at async checkout-web-packages-packages_card-fields-react_src_hook_ts-packages_checkout-graphql_src_in-92a386.latest.en.585aeb6f583627ae41f3.js:1:10995
```

```
ExecutionError: GraphQL execution failed with errors: [
  {
    "message": "invalid id",
    "locations": [
      {
        "line": 1,
        "column": 68
      }
    ],
    "path": [
      "extensionMetafields"
    ]
  }
]
    at checkout-web-packages-packages_card-fields-react_src_hook_ts-packages_checkout-graphql_src_in-92a386.latest.en.585aeb6f583627ae41f3.js:1:8962
    at async s.fetch (app.latest.en.d8134cfd7ee2b0d47f99.js:1:285834)
    at async s.run (checkout-web-packages-packages_card-fields-react_src_hook_ts-packages_checkout-graphql_src_in-92a386.latest.en.585aeb6f583627ae41f3.js:1:11181)
    at async checkout-web-packages-packages_card-fields-react_src_hook_ts-packages_checkout-graphql_src_in-92a386.latest.en.585aeb6f583627ae41f3.js:1:10995
```

I'm not certain but I think it might have to do with some of the UI extension hooks my app require, likely the `useAppMetafields` or something else metafield related. These work as expected in non-b2b checkouts though.

```
const { query } = useExtensionApi();
  const appMetafields = useAppMetafields();
  const currency = useCurrency();
  const extensionSettings = useSettings();
  const extensionData = useExtensionData();
  const checkoutAttributes = useAttributes();
  const shop = useShop();
  const language = useLanguage();
  const cartLines = useCartLines();
  const customer = useCustomer();
  const shippingAddress = useShippingAddress();
  const totalAmount = useTotalAmount();
```

I also do specify 4 metafields in my `extensions.toml`

**Comment by jamesvidler** [comment]
Hi @KTruong008, would to be able to provide the contents of your `toml` file for review?

**Comment by KTruong008** [comment]
> Hi @KTruong008, would to be able to provide the contents of your `toml` file for review?

@jamesvidler Here you go!

```
...
extension_points = [
  'Checkout::Contact::RenderAfter',
  'Checkout::DeliveryAddress::RenderBefore',
  'Checkout::Actions::RenderBefore',
  'Checkout::ShippingMethods::RenderBefore',
  'Checkout::ShippingMethods::RenderAfter',
  'Checkout::CartLineDetails::RenderAfter',
  'Checkout::CartLines::RenderAfter',
  'Checkout::Reductions::RenderBefore',
  'Checkout::Reductions::RenderAfter',
  'Checkout::CustomerInformation::RenderAfter',
  'Checkout::Dynamic::Render',
]

[capabilities]
network_access = false
block_progress = true
api_access = true

[[metafields]]
namespace = "checkout_sales_buddy"
key = "app_settings"

[[metafields]]
namespace = "checkout_sales_buddy"
key = "promotions_one"

[[metafields]]
namespace = "checkout_sales_buddy"
key = "promotions_two"

[[metafields]]
namespace = "checkout_sales_buddy"
key = "promotions_three"


# Read more on extension settings at https://shopify.dev/api/checkout-extensions/checkout/configuration
# [[settings.fields]]
# key = "heading"
# name = "Heading"
# type = "single_line_text_field"

# 18/20 settings
[settings]
  # Fixed promotion id(s)
  [[settings.fields]]
  key = "fixed_promotion_id"
  type = "single_line_text_field"
  name = "Fixed promotion ID"
  description = "Ensure a specific promotion(s) show. Separate multiple IDs with a comma."
    [[settings.fields.validations]]
    name = "regex"
    value = "^([0-9])*((,[ ]*)([0-9]*)([ ])*)*$"
    ...
```

**Comment by KTruong008** [comment]
> Is this happening when running the extension locally (using `yarn dev`) and also after the extension has been installed and activated in a checkout?

Just tested locally and it's not showing up on B2B checkouts either, though the error looks a bit different:

```
ExecutionError: GraphQL execution failed with errors: [
  {
    "message": "invalid id",
    "locations": [
      {
        "line": 1,
        "column": 78
      }
    ],
    "path": [
      "appMetafields"
    ]
  }
]
    at checkout-web-packages-packages_card-fields-react_src_hook_ts-packages_checkout-graphql_src_in-92a386.latest.en.585aeb6f583627ae41f3.js:1:8962
    at async s.fetch (app.latest.en.079cd2fbb6a2f15d643e.js:1:287829)
    at async s.run (checkout-web-packages-packages_card-fields-react_src_hook_ts-packages_checkout-graphql_src_in-92a386.latest.en.585aeb6f583627ae41f3.js:1:11181)
    at async checkout-web-packages-packages_card-fields-react_src_hook_ts-packages_checkout-graphql_src_in-92a386.latest.en.585aeb6f583627ae41f3.js:1:10995
```

First time it happened was in production (installed and activated in checkout) a couple weeks ago. Didn't think much of it but it happened again a couple days ago.

**Comment by KTruong008** [comment]
Nope, it's been happening all this time as far as I know, I just took notice recently. Every time I've tried it in a B2B checkout this issue appears.

**Comment by dnagoda** [comment]
Connected to [Missing session during C1 query: ExtensionMetafields#424002](https://github.com/Shopify/shopify/issues/424002).

**Comment by dnagoda** [comment]
@KTruong008 We just shipped a fix for this! Please let us know if this resolves the bug for you.

**Comment by dnagoda** [comment]
@KTruong008 Thanks for taking a look. Is the error you're seeing in production or just when running a dev preview?

**Comment by KTruong008** [comment]
@dnagoda Those errors were in production, I haven't spun up my dev environment for testing yet.
